[theme]
primaryColor = "#d32f2f"
backgroundColor = "#f4f7fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#212121"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
runOnSave = false
